"""Extra tests for PythonParser covering edge cases not in test_python_parser.py.

Patterns covered:
- Aliased imports (import X as Y) — lines 147-150
- Bare relative imports (from . import X) — line 173
- Dotted base class (class Foo(module.Bar)) — line 641
- Class without docstring — line 571
- Parser language property and can_parse
"""

from __future__ import annotations

from pathlib import Path

import pytest
from codeindex.models import EdgeKind
from codeindex.parser.python_parser import PythonParser


@pytest.fixture()
def parser() -> PythonParser:
    """Provide a fresh PythonParser instance."""
    return PythonParser()


@pytest.fixture()
def parsed_extras(python_extras_fixture_path: Path):
    """Parse python_extras.py and return (nodes, edges).

    Args:
        python_extras_fixture_path: Path to the extras fixture.

    Returns:
        Tuple of (nodes, edges).
    """
    return PythonParser().parse(str(python_extras_fixture_path))


# ──────────────────────────────────────────────
# Parser metadata
# ──────────────────────────────────────────────


class TestPythonParserMetadata:
    """Tests for parser properties and can_parse."""

    def test_language_property(self, parser: PythonParser) -> None:
        """language property returns 'python'."""
        assert parser.language == "python"

    def test_extensions(self, parser: PythonParser) -> None:
        """extensions returns ['.py']."""
        assert parser.extensions == [".py"]

    def test_can_parse_py(self, parser: PythonParser) -> None:
        """can_parse returns True for .py files."""
        assert parser.can_parse("src/foo.py")

    def test_cannot_parse_js(self, parser: PythonParser) -> None:
        """can_parse returns False for .js files."""
        assert not parser.can_parse("src/foo.js")

    def test_cannot_parse_ts(self, parser: PythonParser) -> None:
        """can_parse returns False for .ts files."""
        assert not parser.can_parse("src/foo.ts")


# ──────────────────────────────────────────────
# Aliased imports — import X as Y
# ──────────────────────────────────────────────


class TestPythonAliasedImports:
    """Tests for IMPORTS_FROM edges generated by 'import X as Y' statements."""

    def test_aliased_import_creates_edge(self, parsed_extras) -> None:
        """import os as opsys creates an IMPORTS_FROM edge targeting 'os'."""
        _, edges = parsed_extras
        import_targets = {e.target for e in edges if e.kind == EdgeKind.IMPORTS_FROM}
        assert "os" in import_targets

    def test_aliased_import_target_is_original_name(self, parsed_extras) -> None:
        """The edge target is the original module name, not the alias."""
        _, edges = parsed_extras
        import_targets = {e.target for e in edges if e.kind == EdgeKind.IMPORTS_FROM}
        # The alias 'opsys' must NOT appear as an import target
        assert "opsys" not in import_targets

    def test_multiple_aliased_imports(self, parsed_extras) -> None:
        """Both 'import os as opsys' and 'import sys as system' create edges."""
        _, edges = parsed_extras
        import_targets = {e.target for e in edges if e.kind == EdgeKind.IMPORTS_FROM}
        assert "sys" in import_targets


# ──────────────────────────────────────────────
# Bare relative imports — from . import X
# ──────────────────────────────────────────────


class TestPythonBareRelativeImport:
    """Tests for bare relative imports (from . import X)."""

    def test_bare_relative_import_uses_name_as_target(self, parsed_extras) -> None:
        """'from . import helpers' creates an IMPORTS_FROM edge targeting 'helpers'.

        The parser picks up the dotted_name child of the import_from_statement,
        which for ``from . import helpers`` is the imported name itself.
        """
        _, edges = parsed_extras
        import_targets = {e.target for e in edges if e.kind == EdgeKind.IMPORTS_FROM}
        assert "helpers" in import_targets

    def test_bare_relative_import_does_not_produce_empty_target(self, parsed_extras) -> None:
        """No IMPORTS_FROM edge has an empty string as target."""
        _, edges = parsed_extras
        import_targets = {e.target for e in edges if e.kind == EdgeKind.IMPORTS_FROM}
        assert "" not in import_targets


# ──────────────────────────────────────────────
# Dotted base class — class Foo(module.Bar)
# ──────────────────────────────────────────────


class TestPythonDottedBaseClass:
    """Tests for INHERITS edges from dotted base class references."""

    def test_dotted_base_creates_inherits_edge(self, parsed_extras) -> None:
        """class Extended(os.PathLike) creates an INHERITS edge."""
        _, edges = parsed_extras
        inherits = [e for e in edges if e.kind == EdgeKind.INHERITS]
        assert len(inherits) >= 1

    def test_dotted_base_target_includes_attr(self, parsed_extras) -> None:
        """The INHERITS edge target contains the attribute name."""
        _, edges = parsed_extras
        inherits_targets = {e.target for e in edges if e.kind == EdgeKind.INHERITS}
        # os.PathLike is the full dotted name
        assert any("PathLike" in t for t in inherits_targets)


# ──────────────────────────────────────────────
# Class with no docstring
# ──────────────────────────────────────────────


class TestPythonNoDocstring:
    """Tests for nodes without docstrings."""

    def test_nodocs_class_has_no_docstring(self, parsed_extras) -> None:
        """NoDocs class has no docstring — _get_docstring returns None."""
        nodes, _ = parsed_extras
        no_docs = next((n for n in nodes if n.name == "NoDocs"), None)
        assert no_docs is not None
        assert no_docs.docstring is None

    def test_base_class_has_docstring(self, parsed_extras) -> None:
        """Base class does have a docstring."""
        nodes, _ = parsed_extras
        base = next((n for n in nodes if n.name == "Base"), None)
        assert base is not None
        assert base.docstring is not None


# ──────────────────────────────────────────────
# Inline / minimal Python snippets
# ──────────────────────────────────────────────


class TestPythonInlineSnippets:
    """Tests for small inline Python programs written to tmp files."""

    def test_function_without_docstring(self, tmp_path: Path) -> None:
        """Function with no docstring has docstring=None."""
        f = tmp_path / "nodoc.py"
        f.write_text("def plain():\n    return 1\n", encoding="utf-8")
        nodes, _ = PythonParser().parse(str(f))
        fn = next(n for n in nodes if n.name == "plain")
        assert fn.docstring is None

    def test_aliased_from_import_creates_edge(self, tmp_path: Path) -> None:
        """'from flask import Flask as App' creates IMPORTS_FROM edge for 'flask'."""
        f = tmp_path / "alias_from.py"
        f.write_text("from flask import Flask as App\n", encoding="utf-8")
        _, edges = PythonParser().parse(str(f))
        import_targets = {e.target for e in edges if e.kind == EdgeKind.IMPORTS_FROM}
        assert "flask" in import_targets

    def test_class_with_only_pass_no_docstring(self, tmp_path: Path) -> None:
        """A class whose body is just 'pass' has no docstring."""
        f = tmp_path / "passonly.py"
        f.write_text("class Empty:\n    pass\n", encoding="utf-8")
        nodes, _ = PythonParser().parse(str(f))
        cls = next(n for n in nodes if n.name == "Empty")
        assert cls.docstring is None

    def test_self_method_call_generates_calls_edge(self, tmp_path: Path) -> None:
        """self.validate() from within a method generates a CALLS edge."""
        f = tmp_path / "calls.py"
        f.write_text(
            "class Svc:\n"
            "    def run(self):\n"
            "        return self.validate()\n"
            "    def validate(self):\n"
            "        return True\n",
            encoding="utf-8",
        )
        _, edges = PythonParser().parse(str(f))
        calls = [e for e in edges if e.kind == EdgeKind.CALLS]
        assert any("run" in e.source and "validate" in e.target for e in calls)

    def test_class_method_call_same_class(self, tmp_path: Path) -> None:
        """Calling another function in the same class by name resolves to a CALLS edge."""
        f = tmp_path / "same_class.py"
        f.write_text(
            "class Svc:\n"
            "    def run(self):\n"
            "        return self.helper()\n"
            "    def helper(self):\n"
            "        return 42\n",
            encoding="utf-8",
        )
        _, edges = PythonParser().parse(str(f))
        calls = [e for e in edges if e.kind == EdgeKind.CALLS]
        assert any("run" in e.source and "helper" in e.target for e in calls)
